### ISSUE TITLE
Weapons with attachments in LintedItems class are not selectable

### ISSUE THREAD

**Issue by alexsaurber** [jetelain/AceArsenalExtended#17]
I was making a compat patch for the rest of the weapons in the Tier 1 Weapons mod and noticed something that I had to rack my brain over. Weapons that have linkeditems do not play nice and cannot be selected via options. The remedy for this is to add `delete LinktedItems;` to the weapon class. Only if there are no attachments attached by default will the weapons be selectable via the options you define. Not sure if there is a way for you to take care of this or not, but it would be good for other users to take note. This causes compatibility for any machinegun that comes with a bipod as default to not be stackable.

I see this was a feature under the https://github.com/jetelain/AceArsenalExtended/blob/c7e1651bb57367219857f4eec1f19ce7c2b0d41c/addons/gearinfo/functions/script_component.hpp file, what is the reasoning for that? Suppressing class names of weapons with grips, such as `Tier1_MK46_Mod1_Savit_KACGrip_Desert`?

See below.

```
    class Tier1_MK48_Mod0_Para_Desert : Tier1_MK48_Mod0
	{
		class XtdGearInfo
		{
			model = "ax_mk48mod";
			camo = "desert";
			revision = "mk48mod0";
			version = "para";
		};
		delete LinkedItems;
	};
```

Thanks!

**Comment by jetelain** [comment]
Hi,

It's a consequence of RHS and CBA way of handling grips : for each supported grip, there is an alternate version of the CfgWeapons entry to associate the correct hand animation. So those entries are filtered out with LinkedItems for that reason.

Typical example (from AMF) :
```
class AMF_614_long_01_F : AMF_614_long_01_Base_F
{
	scope=2;
	...
};
class amf_614_gripv_01_f : AMF_614_long_01_F
{
	...
	handAnim[]={"OFP2_ManSkeleton", "\AMF_614\anim\amf_hand_gripV.rtm"};
	class LinkedItems
	{
		...
	};
};
class amf_614_gript_01_f : AMF_614_long_01_F
{
	...
	handAnim[]={"OFP2_ManSkeleton", "\AMF_614\anim\amf_hand_gripT.rtm"};
	class LinkedItems
	{
		...
	};
};
```
I don't know how ACE filter them, I'm going to have a look.

**Comment by jetelain** [comment]
They rely on bis_fnc_baseWeapon

**Comment by jetelain** [comment]
A way to fix it :
- Remove the LinkedItems criteria to the macro
- Create a second pass filter to exclude weapons that are not they own base weapon : 
  - if `(isClass (_x >> "WeaponSlotsInfo") && { count (_x >> "linkeditems") != 0 } )` (weapons with LinkedItems)
    - look for `gettext (_x >> "baseWeapon")`, if name match keep entry, if name mismatch ignore entry 
    - look for a parent class (inheritsFrom / BIS_fnc_returnParents) that match macro but have no LinkedItems, if exists ignore entry
  - otherwise keep entry

This should be OK for Tier1_MK48_Mod0_Para_Desert and it's parent Tier1_MK48_Mod0
-  class Tier1_MK48_Mod0_Para_Desert  => scope=2 (Macro OK), count LinkedItems = 1
-  class Tier1_MK48_Mod0  => scope=2 (Macro OK), count LinkedItems = 1
-  class Tier1_SAW_Base => scope=1 (Macro will filter), count LinkedItems = 0
- ... scope=1
